name: EXAMEN Workflow
on:
  push:
    branches:
      - main
jobs:
  repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-python@v4
        with:
            node-version: 'alpine'
      - name: Dependencias
        run: |
          npm install


  image-to-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/sandra-eyo/examen-back /back-image:latest
